# Generated by Django 4.2.2 on 2023-07-16 15:35

from django.db import migrations, models
import django_nepali.models.nepalidate


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NepaliDateFieldTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nepali_date_extrafield_str",
                    django_nepali.models.nepalidate.NepaliDateCharField(
                        blank=True, max_length=10
                    ),
                ),
                ("nepali_date", django_nepali.models.nepalidate.NepaliDateField()),
            ],
        ),
    ]
